acts/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     path('', Acts, name='acts'),
     path('addact/', AddAct, name='add_act'),
     path('acts_list/', ActsList.as_view(), name='acts_list'),
     path('act_edit/<int:act_id>', ActEdit, name='act_edit'),
     path('act_delete/<int:act_id>', ActDelete, name='act_delete'),
     path('generate_act_document/<int:act_id>', GenerateActDocument,
          name='generate_act_document'),
     path('get_acts/', get_acts, name='get_acts'),
     path('create_based_on_act/<int:act_id>',
          CreateBasedOnAct, name='create_based_on_act'),
     path('upload-data-acts/', upload_data_acts, name='upload_data_acts'),
     path('add_os/', add_os, name='add_os'),
     path('updstatus/<int:pk>/', UpdateStatus, name='updstatus'),
     path('dem_act/', GenerateDismantlingDocument, name='dem_act'),

]

complectations/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', Complectations,  name='complectations'),
    path('complectations_list/', ComplectationsList.as_view(), name='complectations_list'),
    path('add_complectations/', AddComplectations, name='add_complectations'),

]

dbdit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('acts/', include('acts.urls')),
    path('complectations/', include('complectations.urls')),
    path('directories/', include('directories.urls')),
    path('moves/', include('moves.urls')),
    path('applications/', include('applications.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('', RedirectView.as_view(url='index/', permanent=True)),
    path('select2/', include('django_select2.urls', namespace='django_select2')),
    path('loadsql/', include('loadsql.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

complectations/models.py
from django.db import models
from acts.models import *
from directories.models import *
#from заявки import *


class Complectations(models.Model):
    avtor = models.CharField(max_length=100)
    date = models.DateField(auto_now_add=True)
    par_doc = models.ForeignKey(Acts, on_delete=models.PROTECT, blank=True, null=True)
    inv_dit = models.ForeignKey(IT_OS, on_delete = models.PROTECT)
    new_name_os = models.CharField(max_length=255)
    tmc = models.ForeignKey(Tmc, on_delete=models.PROTECT, blank=True, default=None)
    tmc_qty = models.IntegerField()
    prev_name_os = models.CharField(max_length=255, default="None")
    doc_num = models.IntegerField(blank=True, default=1)

    def __str__(self):
        return f"{self.date} {self.inv_dit}"
    
    class Meta:
        managed = True
        db_table = 'Complectations'

complectations/forms.py
from django import forms
from . import models
from directories.models import IT_OS
from django_select2.forms import Select2Widget, Select2MultipleWidget, ModelSelect2Widget, ModelSelect2MultipleWidget


class ComplForm(forms.ModelForm):
    
    prev_name_os = forms.CharField(widget=forms.TextInput(attrs={'id': 'prev_name'})
                                   )

    avtor = forms.CharField(
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Получаем пользователя из аргументов
        super(ComplForm, self).__init__(*args, **kwargs)
        if user:
            # Устанавливаем начальное значение поля 'avtor'
            self.initial['avtor'] = user.get_username()

    class Meta:
        model = models.Complectations
        fields = ['par_doc', 'inv_dit', 'new_name_os', 'tmc', 'tmc_qty','prev_name_os']
        widgets = {
            "inv_dit": ModelSelect2Widget(
                attrs={'class': 'form-field inv_dit',
                       }, 
                       search_fields=['inv_dit__icontains'],
            ),
            "new_name_os": forms.TextInput(attrs={'class': 'form-field text',
                                                  'id': 'new_name_os'}),
            "par_doc": ModelSelect2Widget(attrs={'class': 'form-field text'},
                                          search_fields=['pk__icontains'],),
            "tmc": ModelSelect2MultipleWidget(attrs={'class': 'form-field select multi'},
                                              search_fields=['tmc_name__icontains']),
            "tmc_qty": forms.NumberInput(attrs={'class': 'form-field'}),
        }

        def save(self, commit=True):
            instance = super().save(commit=False)
            
            new_name_os = self.cleaned_data.get('new_name_os')
            
            if new_name_os:
                it_os_instance = instance.inv_dit
                it_os_instance.name_os = new_name_os
                it_os_instance.save()

            if commit:
                instance.save()
            return instance

complectations/views.py
from django.contrib.auth.decorators import login_required
from . import forms
from . import models
from django.apps import apps
from openpyxl import load_workbook
from django.http import JsonResponse
from django.http import HttpResponse
from django_datatables_view.base_datatable_view import BaseDatatableView
import os
from django.conf import settings
import subprocess
from django.db.models import Q, F, Value, CharField
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from docxtpl import DocxTemplate

import tempfile
from django.db.models.functions import Lower
from django.db.models import CharField
from django.contrib import messages
import pandas as pd


@login_required
def Complectations(request):
    return render(request, 'complectations/complectations.html')


class ComplectationsList(BaseDatatableView):
    model = apps.get_model('complectations', 'Complectations')
    columns = ['pk', 'date', 'avtor', 'inv_dit', 'tmc', 'tmc_qty', 'par_doc']

    def render_column(self, row, column):
        if column == 'tmc':
            return ', '.join([str(tmc) for tmc in row.tmc.all()])

        if column == 'date':
            if row.date is not None:
                return row.date.strftime('%d.%m.%Y')
            else:
                return ''
        return super().render_column(row, column)

    def filter_queryset(self, qs):
        search_value = self.request.GET.get('search[value]', '')
        if search_value:
            search_terms = search_value.lower().split()
            query = Q()
            for term in search_terms:
                query |= Q(inv_dit__inv_dit__iregex=r'(?i)^.+' +
                           term[1:]) | Q(tmc__tmc_name__iregex=r'(?i)^.+' + term[1:])
            qs = qs.filter(query).distinct()  # Применяем distinct() здесь
        return qs


############ Создать документ комплектации ############

def AddComplectations(request):

    if request.method == 'POST':
        form = forms.ComplForm(request.POST, user=request.user)
        if form.is_valid():
            act = form.save(commit=False)
            act.avtor = request.user
            act.save()
            form.save_m2m()
            return redirect('complectations')
    else:
        form = forms.ComplForm(user=request.user)

    return render(request, 'complectations/add_complectations.html', {'form': form})

complectations/templates/complectations/add_complectations.html
{% extends "index/base.html" %}

{% block title %}Создать комплектацию{% endblock %}

{% block document-name %}<h2 class="form-title">Создать комплектацию ОС</h2>{% endblock %}

{% block document-buttons %}

{% endblock %}

{% block content %}



    <div class="form-container">

        <a type="hidden">{{ form.media }}</a>

        <form method="post" action="{% url 'add_complectations' %}" class="form-area act">

            {% csrf_token %}
            
            <div>
                <label>Оборудование:</label>
                {{ form.inv_dit }}
            </div>

            <div>
                <label>Новое наименование:</label>
                {{ form.new_name_os }}
            </div>            

            <div>
                <label>ТМЦ:</label>
                {{ form.tmc }}
            </div>

            <div>
                <label>Кол-во:</label>
                {{ form.tmc_qty }}
            </div>      

            <div>
                <label for="id_par_doc">Документ основание:</label>
                {{ form.par_doc }}
            </div>

            <div>
                <label>Автор:</label>
                {{ form.avtor }}
            </div>

            <div style='display: none'>
                <label>Старое имя:</label>
                {{ form.prev_name_os }}
            </div>

            <div class="form-field button">
                <button type="submit">Добавить</button>
            </div>

        </form>

    </div>

{% endblock %}

complectations/templates/complectations/complectations.html
{% extends "index/base.html" %}

{% block title %}Комплектации{% endblock %}

{% block document-buttons %}
    <a class = "AddDocument" href="{% url 'add_complectations' %}" title="Создать новый документ"><span class="create-new-document"></span></a>

    <div id="uploadModal" class="modal" style="display: none;">
        <div class="modal-content">
            <span class="close" onclick="closeFileUploadDialog()">&times;</span>
            {% csrf_token %}
            {% comment %} <div id="file-upload" data-upload-url="{% url 'upload_data_os' %}">
    
                <form id="uploadForm" action="{% url 'upload_data_os' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="file" id="uploadedFile" form="uploadForm">
                    <button type="submit">Загрузить</button>
                </form>
            </div> {% endcomment %}
        </div>
    </div>
    
    <div id="table-pagination" class="step-links"></div>

    <div class="table-options">

        <div class="table-length_main">

            <select id="table_os_length" name="table_os_length">
                <option value="10">10</option>
                <option value="25">25</option>
                <option value="50" selected>50</option>
                <option value="100">100</option>
            </select>

        </div>

    </div>

{% endblock %}


{% block content %}
    <div class="contentpanel">

        <div class="table-container">

            <table id="table_complectations" class="display" style="width:100%">

                <thead>

                    <tr>

                        <th>№</th>
                        <th>Дата</th>
                        <th>Автор</th>
                        <th>Основное средство</th>
                        <th>ТМЦ</th>
                        <th>Кол-во</th>
                        <th>Основание</th>
                    </tr>

                </thead>

            </table>

        </div>

    </div>
{% endblock %}